---
# Install AWS Plugin (see https://github.com/elasticsearch/elasticsearch-cloud-aws)
#
# The following variables need to be defined in your playbook or inventory:
# - elasticsearch_plugin_aws_version
#
# The following variables provide a for now limited configuration for the plugin.
# More options may be available in the future.
# (see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-discovery-ec2.html):
# - elasticsearch_plugin_aws_ec2_groups
# - elasticsearch_plugin_aws_ec2_ping_timeout
# - elasticsearch_plugin_aws_access_key
# - elasticsearch_plugin_aws_secret_key


- name: Installing AWS Plugin
  action: >
    shell bin/plugin -install elasticsearch/elasticsearch-cloud-aws/{{ elasticsearch_plugin_aws_version }}
    chdir={{ elasticsearch_home_dir }}
# Fix permissions
- file: >
    path="{{ elasticsearch_plugin_dir }}" state=directory
    owner={{ elasticsearch_user }} group={{ elasticsearch_group }}
    recurse=yes
# Configure AWS Plugin
- name: Configuring AWS Plugin
  lineinfile: >
    dest="{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    regexp='^(discovery.type: ec2)$'
    insertafter='^(#*\sDiscovery\s#*)$'
    line="discovery.type: ec2"
- lineinfile: >
    dest="{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    regexp='^(discovery.ec2.groups.*)$'
    insertafter='^(discovery.type: ec2)$'
    line="discovery.ec2.groups: '{{ elasticsearch_plugin_aws_ec2_groups }}'"
- lineinfile: >
    dest="{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    regexp='^(discovery.ec2.ping_timeout.*)$'
    insertafter='^(discovery.ec2.groups.*)$'
    line="discovery.ec2.ping_timeout: {{ elasticsearch_plugin_aws_ec2_ping_timeout }}"
- lineinfile: >
    dest="{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    regexp='^(cloud.node.auto_attributes.*)$'
    insertafter='^(discovery.ec2.ping_timeout.*)$'
    line="cloud.node.auto_attributes: true"
- lineinfile: >
    dest="{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    regexp='^(cloud.aws.access_key.*)$'
    insertafter='^(cloud.node.auto_attributes.*)$'
    line="cloud.aws.access_key: '{{ elasticsearch_plugin_aws_access_key }}'"
- lineinfile: >
    dest="{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    regexp='^(cloud.aws.secret_key.*)$'
    insertafter='^(cloud.aws.access_key.*)$'
    line="cloud.aws.secret_key: '{{ elasticsearch_plugin_aws_secret_key }}'"
